<?php

namespace Database\Seeders;

use App\Models\BankSoal;
use Illuminate\Database\Seeder;

class BankSoalSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $soalList = [
            [
                'soal'              => 'Dalam prosedur Penanggulangan Kebakaran (Code Red) di rumah sakit, langkah pertama yang harus dilakukan sesuai prinsip PASS saat menggunakan APAR adalah...',
                'opsi_a'            => 'Pull (Tarik pin pengaman APAR)',
                'opsi_b'            => 'Aim (Arahkan nozzle ke pangkal titik api)',
                'opsi_c'            => 'Squeeze (Tekan tuas pegangan APAR)',
                'opsi_d'            => 'Sweep (Sapukan dari sisi ke sisi secara merata)',
                'kunci_jawaban'     => 'A',
                'tingkat_kesulitan' => 'mudah',
                'is_selected'       => true,
            ],
            [
                'soal'              => 'Berdasarkan standar WHO di rumah sakit, momen pertama dari 5 Momen Kebersihan Tangan (5 Moments for Hand Hygiene) adalah...',
                'opsi_a'            => 'Sebelum menyentuh pasien',
                'opsi_b'            => 'Sebelum melakukan prosedur bersih / aseptik',
                'opsi_c'            => 'Setelah terkena cairan tubuh pasien',
                'opsi_d'            => 'Setelah menyentuh lingkungan sekitar pasien',
                'kunci_jawaban'     => 'A',
                'tingkat_kesulitan' => 'mudah',
                'is_selected'       => true,
            ],
            [
                'soal'              => 'Durasi waktu yang direkomendasikan WHO untuk melakukan cuci tangan menggunakan cairan berbasis alkohol (alcohol handrub) adalah...',
                'opsi_a'            => '5 - 10 detik',
                'opsi_b'            => '20 - 30 detik',
                'opsi_c'            => '40 - 60 detik',
                'opsi_d'            => '2 - 3 menit',
                'kunci_jawaban'     => 'B',
                'tingkat_kesulitan' => 'mudah',
                'is_selected'       => true,
            ],
            [
                'soal'              => 'Salah satu dari 6 Sasaran Keselamatan Pasien (SKP) di Rumah Sakit adalah identifikasi pasien secara akurat. Minimal berapa indikator utama yang wajib digunakan untuk mengidentifikasi pasien?',
                'opsi_a'            => '1 indikator (Hanya Nomor Rekam Medis)',
                'opsi_b'            => '2 indikator (Nama Lengkap dan Tanggal Lahir)',
                'opsi_c'            => '3 indikator (Nama, Alamat, dan Nomor Kamar)',
                'opsi_d'            => '4 indikator (Nama, Dokter DPJP, Agama, dan NIK)',
                'kunci_jawaban'     => 'B',
                'tingkat_kesulitan' => 'mudah',
                'is_selected'       => true,
            ],
            [
                'soal'              => 'Dalam sistem kode darurat rumah sakit (Emergency Code), kode darurat "Code Blue" mengindikasikan adanya situasi...',
                'opsi_a'            => 'Henti jantung / henti napas (Kedaruratan Medis)',
                'opsi_b'            => 'Ancaman kebakaran di area gedung RS',
                'opsi_c'            => 'Penculikan bayi atau anak di lingkungan RS',
                'opsi_d'            => 'Bencana alam dan evakuasi eksternal',
                'kunci_jawaban'     => 'A',
                'tingkat_kesulitan' => 'mudah',
                'is_selected'       => true,
            ],
            [
                'soal'              => 'Kode darurat keselamatan di rumah sakit yang menandakan adanya bahaya atau ancaman kebakaran adalah...',
                'opsi_a'            => 'Code Pink',
                'opsi_b'            => 'Code Black',
                'opsi_c'            => 'Code Red',
                'opsi_d'            => 'Code Yellow',
                'kunci_jawaban'     => 'C',
                'tingkat_kesulitan' => 'mudah',
                'is_selected'       => true,
            ],
            [
                'soal'              => 'Urutan pelepasan Alat Pelindung Diri (APD) yang benar setelah merawat pasien infeksius untuk mencegah kontaminasi silang adalah...',
                'opsi_a'            => 'Sarung tangan, Gown/Skort, Goggle/Pelindung mata, Masker',
                'opsi_b'            => 'Masker, Sarung tangan, Gown, Goggle',
                'opsi_c'            => 'Gown, Masker, Goggle, Sarung tangan',
                'opsi_d'            => 'Goggle, Masker, Sarung tangan, Gown',
                'kunci_jawaban'     => 'A',
                'tingkat_kesulitan' => 'normal',
                'is_selected'       => true,
            ],
            [
                'soal'              => 'Kantong plastik berwarna kuning pada tempat sampah di ruang perawatan rumah sakit diperuntukkan khusus bagi jenis limbah...',
                'opsi_a'            => 'Limbah infeksius dan kontaminasi cairan tubuh/darah',
                'opsi_b'            => 'Limbah non-infeksius / domestik seperti sisa makanan dan kertas',
                'opsi_c'            => 'Limbah sitotoksik dan sisa obat kanker',
                'opsi_d'            => 'Limbah radioaktif dari instalasi radiologi',
                'kunci_jawaban'     => 'A',
                'tingkat_kesulitan' => 'mudah',
                'is_selected'       => true,
            ],
            [
                'soal'              => 'Syarat pengisian wadah limbah benda tajam (Safety Box / Sharp Container) adalah harus ditutup rapat dan diganti apabila sudah terisi...',
                'opsi_a'            => '1/4 bagian',
                'opsi_b'            => '3/4 bagian',
                'opsi_c'            => 'Penuh meluap (100%)',
                'opsi_d'            => '1/2 bagian',
                'kunci_jawaban'     => 'B',
                'tingkat_kesulitan' => 'normal',
                'is_selected'       => true,
            ],
            [
                'soal'              => 'Rasio kompresi dada dan ventilasi napas bantuan pada tindakan Resusitasi Jantung Paru (RJP/CPR) dewasa dengan 1 atau 2 penolong adalah...',
                'opsi_a'            => '15 kompresi : 2 ventilasi',
                'opsi_b'            => '30 kompresi : 2 ventilasi',
                'opsi_c'            => '50 kompresi : 5 ventilasi',
                'opsi_d'            => '10 kompresi : 1 ventilasi',
                'kunci_jawaban'     => 'B',
                'tingkat_kesulitan' => 'normal',
                'is_selected'       => true,
            ],
            [
                'soal'              => 'Berdasarkan panduan American Heart Association (AHA), kecepatan kompresi dada berkualitas tinggi (High Quality CPR) pada pasien dewasa adalah...',
                'opsi_a'            => '60 - 80 kali per menit',
                'opsi_b'            => '100 - 120 kali per menit',
                'opsi_c'            => '140 - 160 kali per menit',
                'opsi_d'            => '80 - 90 kali per menit',
                'kunci_jawaban'     => 'B',
                'tingkat_kesulitan' => 'normal',
                'is_selected'       => true,
            ],
            [
                'soal'              => 'Komunikasi verbal atau lewat telepon antar Profesional Pemberi Asuhan (PPA) di rumah sakit wajib menggunakan teknik SBAR. Kepanjangan dari SBAR adalah...',
                'opsi_a'            => 'Situation, Background, Assessment, Recommendation',
                'opsi_b'            => 'Symptom, Body, Action, Response',
                'opsi_c'            => 'Situation, Biological, Analysis, Remedy',
                'opsi_d'            => 'Status, Background, Action, Result',
                'kunci_jawaban'     => 'A',
                'tingkat_kesulitan' => 'normal',
                'is_selected'       => true,
            ],
            [
                'soal'              => 'Saat menerima instruksi lisan atau telepon dari dokter DPJP, perawat wajib melakukan verifikasi keselamatan pasien dengan metode...',
                'opsi_a'            => 'Tulis, Baca Kembali, dan Konfirmasi ulang (TULBAKON)',
                'opsi_b'            => 'Dengarkan, Catat, dan Langsung laksanakan',
                'opsi_c'            => 'Tulis, Kirim Pesan Singkat, dan Tunggu balasan',
                'opsi_d'            => 'Baca saja tanpa perlu mencatat',
                'kunci_jawaban'     => 'A',
                'tingkat_kesulitan' => 'mudah',
                'is_selected'       => true,
            ],
            [
                'soal'              => 'Obat-obatan yang termasuk dalam kategori High Alert Medications (Obat Kewaspadaan Tinggi) di rumah sakit harus diberi penandaan label khusus berwarna...',
                'opsi_a'            => 'Hijau muda',
                'opsi_b'            => 'Merah menyala',
                'opsi_c'            => 'Biru tua',
                'opsi_d'            => 'Kuning pekat',
                'kunci_jawaban'     => 'B',
                'tingkat_kesulitan' => 'normal',
                'is_selected'       => true,
            ],
            [
                'soal'              => 'Penyimpanan obat dengan nama, kemasan, atau ucapan mirip (LASA - Look Alike Sound Alike) di Instalasi Farmasi diatur dengan memberikan stiker khusus bertuliskan...',
                'opsi_a'            => 'LASA / NORUM',
                'opsi_b'            => 'EXPIRED',
                'opsi_c'            => 'DANGER',
                'opsi_d'            => 'NARKOTIKA',
                'kunci_jawaban'     => 'A',
                'tingkat_kesulitan' => 'mudah',
                'is_selected'       => true,
            ],
            [
                'soal'              => 'Pengkajian risiko jatuh pada pasien dewasa rawat inap di rumah sakit secara berkala menggunakan instrumen penilaian...',
                'opsi_a'            => 'Humpty Dumpty Scale',
                'opsi_b'            => 'Morse Fall Scale (MFS)',
                'opsi_c'            => 'Norton Scale',
                'opsi_d'            => 'Braden Scale',
                'kunci_jawaban'     => 'B',
                'tingkat_kesulitan' => 'normal',
                'is_selected'       => true,
            ],
            [
                'soal'              => 'Pengkajian risiko jatuh yang digunakan khusus untuk pasien anak-anak (pediatrik) di ruang perawatan anak adalah...',
                'opsi_a'            => 'Morse Fall Scale',
                'opsi_b'            => 'Humpty Dumpty Scale',
                'opsi_c'            => 'Barthel Index',
                'opsi_d'            => 'Glasgow Coma Scale',
                'kunci_jawaban'     => 'B',
                'tingkat_kesulitan' => 'normal',
                'is_selected'       => true,
            ],
            [
                'soal'              => 'Salah satu tata cara pencegahan infeksi saluran kemih terkait pemakaian kateter (CAUTI) di rumah sakit adalah...',
                'opsi_a'            => 'Posisikan urine bag di atas ketinggian vesika urinaria pasien',
                'opsi_b'            => 'Menjaga urine bag tetap berada di bawah level kandung kemih dan tidak menyentuh lantai',
                'opsi_c'            => 'Melakukan pembilasan kantong urine secara rutin dengan air kran',
                'opsi_d'            => 'Membiarkan saluran drainase kateter terbuka bebas',
                'kunci_jawaban'     => 'B',
                'tingkat_kesulitan' => 'sulit',
                'is_selected'       => true,
            ],
            [
                'soal'              => 'Jika terjadi pengumuman darurat "Code Pink" melalui pengeras suara rumah sakit, tindakan pertama yang wajib dilakukan oleh petugas keamanan dan seluruh staf RS adalah...',
                'opsi_a'            => 'Mengunci dan mengawasi seluruh akses pintu keluar/gerbang RS serta memeriksa orang yang membawa anak/bayi',
                'opsi_b'            => 'Menutup dan mematikan seluruh aliran listrik rumah sakit',
                'opsi_c'            => 'Mengosongkan gedung RS dan berkumpul di titik kumpul',
                'opsi_d'            => 'Mengambil APAR dan menuju lokasi kejadian',
                'kunci_jawaban'     => 'A',
                'tingkat_kesulitan' => 'normal',
                'is_selected'       => true,
            ],
            [
                'soal'              => 'Perlengkapan yang khusus digunakan untuk membersihkan dan mengamankan tumpahan darah, cairan tubuh, atau bahan kimia infeksius di rumah sakit adalah...',
                'opsi_a'            => 'First Aid Kit',
                'opsi_b'            => 'Spill Kit',
                'opsi_c'            => 'Resusitasi Kit',
                'opsi_d'            => 'Emergency Kit',
                'kunci_jawaban'     => 'B',
                'tingkat_kesulitan' => 'mudah',
                'is_selected'       => true,
            ],
            [
                'soal'              => 'Prinsip ergonomi yang benar saat mengangkat atau memindahkan beban berat/pasien di rumah sakit untuk mencegah cedera tulang belakang adalah...',
                'opsi_a'            => 'Membengkokkan punggung dan menahan beban pada pinggang',
                'opsi_b'            => 'Menjaga punggung tetap lurus dan menumpu beban pada otot paha/kaki',
                'opsi_c'            => 'Memutar badan secara mendadak saat mengangkat beban',
                'opsi_d'            => 'Mengangkat beban melebihi kapasitas tanpa bantuan alat/rekan kerja',
                'kunci_jawaban'     => 'B',
                'tingkat_kesulitan' => 'normal',
                'is_selected'       => true,
            ],
            [
                'soal'              => 'Pernyataan persetujuan tindakan medis yang diberikan oleh pasien atau keluarga sah setelah mendapatkan penjelasan lengkap dari dokter DPJP disebut...',
                'opsi_a'            => 'Informed Consent',
                'opsi_b'            => 'Second Opinion',
                'opsi_c'            => 'Medical Record',
                'opsi_d'            => 'General Consent',
                'kunci_jawaban'     => 'A',
                'tingkat_kesulitan' => 'mudah',
                'is_selected'       => true,
            ],
            [
                'soal'              => 'Kode darurat keselamatan "Code Black" di lingkungan rumah sakit diaktifkan apabila terjadi kondisi...',
                'opsi_a'            => 'Ancaman bom atau kekerasan fisik menggunakan senjata berbahaya',
                'opsi_b'            => 'Kebocoran gas beracun di laboratorium',
                'opsi_c'            => 'Kerusakan sistem jaringan komputer RS',
                'opsi_d'            => 'Kegagalan listrik utama rumah sakit',
                'kunci_jawaban'     => 'A',
                'tingkat_kesulitan' => 'normal',
                'is_selected'       => true,
            ],
            [
                'soal'              => 'Penerapan etika batuk dan bersin yang benar di lingkungan fasilitas kesehatan untuk mencegah penularan droplets adalah...',
                'opsi_a'            => 'Menutup mulut dan hidung menggunakan telapak tangan terbuka',
                'opsi_b'            => 'Menutup mulut dan hidung menggunakan lengan atas bagian dalam atau tisu sekali pakai',
                'opsi_c'            => 'Mengarahkan batuk ke arah rekan kerja di dekatnya',
                'opsi_d'            => 'Membiarkan batuk tanpa ditutup agar sirkulasi udara bebas',
                'kunci_jawaban'     => 'B',
                'tingkat_kesulitan' => 'mudah',
                'is_selected'       => true,
            ],
            [
                'soal'              => 'Dalam Indikator Mutu Nasional (INM) Pelayanan Kesehatan Rumah Sakit, target minimal pencapaian Kepatuhan Kebersihan Tangan (Hand Hygiene) petugas adalah...',
                'opsi_a'            => '50%',
                'opsi_b'            => '75%',
                'opsi_c'            => '85%',
                'opsi_d'            => '100%',
                'kunci_jawaban'     => 'C',
                'tingkat_kesulitan' => 'sulit',
                'is_selected'       => true,
            ],
        ];

        foreach ($soalList as $soalData) {
            BankSoal::updateOrCreate(
                ['soal' => $soalData['soal']],
                $soalData
            );
        }
    }
}
